### ISSUE TITLE
EXIF Orientation Problem in Gallery Photos

### ISSUE THREAD

**Issue by meccano1901** [Pixinn/ezwebgallery#2]
1. There's an issue in the displayed orientation of photos
in the full size photo display.  The thumbnails appear ok.
See this gallery for an example:

http://meccano.crabdance.com/pvr/camera_test_photos/EZWebGallery/

In all sets of 4 photos, the photos should display with the product
labels upright.

Here are three groups of 4 test photos taken with 3 different
digital cameras:

http://meccano.crabdance.com/pvr/camera_test_photos/

Firefox 95 and Windows 10 Picture Viewer display all photos correctly.
See this web page for a detailed technical explanation:

https://www.impulseadventure.com/photo/exif-orientation.html

2. A minor issue is on the Configuration tab - "Short description" is
   misspelled as "Short descritption".

**Comment by Pixinn** [comment]
This is indeed a bug as EZWebGallery _should_ be able to handle the orientation correctly.
I will work on it. Thanks for the report and the samples.

**Comment by Pixinn** [comment]
Fixed in release #2 (tag 0.63)
