### ISSUE TITLE
Orient Skin filename contains Special Character

### ISSUE THREAD

**Issue by meccano1901** [Pixinn/ezwebgallery#3]
The Orient skin references the file "Parchemin+Calligraphy.jpg" but as plus signs are not allowed in URLs
this image does not render in Firefox.  Either the plus sign needs to be changed to a different character,
e.g. underscore, or the plus sign needs to be specially encoded as %2B in URLs.

**Comment by Pixinn** [comment]
You're right and I will correct it. However this background picture is correctly displayed by Firefox in this gallery: https://www.xtof.photo/porfolios/istanbul/
:thinking:

**Comment by meccano1901** [comment]
This newer corrected gallery shows the background image:

http://meccano.crabdance.com/David.Williams/travel/Philippines/Mindanao1985/index.html

This older one does not.  If you try to view the light brown background 
image in a new tab you get a 404 error.

http://meccano.crabdance.com/David.Williams/travel/AsiaTrip1999/index.html

I discovered the problem when I ran a link checker against my rearranged
website, it returned many 404 errors against the background images, e.g.:

http://meccano.crabdance.com/David.Williams/travel/AsiaTrip1999/resources/images/Parchemin+Calligraphy.jpg

David Williams

**Comment by Pixinn** [comment]
Fixed in release #2 (tag 0.63)
