### ISSUE TITLE
[FILE:BaseName] is Removing too many Characters

### ISSUE THREAD

**Issue by meccano1901** [Pixinn/ezwebgallery#4]
The Windows 10 filename 19760000_203_WPH_Al.Williams.jpg should have a
BaseName of 19760000_203_WPH_Al.Williams but 19760000_203_WPH_Al is being used in error.

Only the rightmost period should be used as the delimiter for removing the extension.

---

P.S. I also noted that the Trans-Siberian Railway sample photo gallery on
http://www.ezwebgallery.org/overview/sample-galleries/
no longer exists.

**Comment by Pixinn** [comment]
In what kind of error message did you notice this behavior?

**Comment by meccano1901** [comment]
I don't get an error message, but the captions and/or
watermarks on my gallery photos are incorrect.  I use
periods between names, e.g. firstname.lastname and
only the firstname appears with the photo.

You should be scanning from the right for the first period,
not from the left - see:

https://superuser.com/questions/450603/should-file-names-contain-multiple-periods

David Williams, Edmonton, Alberta, CANADA
***@***.***

**Comment by Pixinn** [comment]
Can you confirm that this executable fixes the issue? 
[EZWebGallery.zip](https://github.com/Pixinn/ezwebgallery/files/7836181/EZWebGallery.zip)

Just deflate the file into the folder were EZWebGallery is installed.

**Comment by meccano1901** [comment]
Yes, this executable fixes issue #4!
Thanks you very much.

David Williams, Edmonton, Alberta, CANADA

**Comment by Pixinn** [comment]
Thanks. I pushed the fix. It is not enough for a whole release so I leave the executable here.

**Comment by meccano1901** [comment]
Christophe,

Unfortunately, I have discovered a big problem with release 0.63,
with or without the latest fix.

On two of my computers it works great.  On the 3rd computer,
my newest and fastest, EZWebGallery fails almost immediately
after starting.  The problem is reproduced as follows:

1. Type in a title
2. Select an input directory for photos

The program fails immediately with this event viewer error:

Log Name:      Application
Source:        Application Error
Date:          2022-01-15 7:54:27 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WILLIAMS10
Description:
Faulting application name: EZWebGallery.exe, version: 0.0.0.0, time 
stamp: 0x61db6c1c
Faulting module name: CORE_RL_magick_.dll, version: 6.9.11.19, time 
stamp: 0x6019898e
Exception code: 0xc0000005
Fault offset: 0x0000000000069885
Faulting process id: 0x534
Faulting application start time: 0x01d80a1fc670154f
Faulting application path: C:\Program 
Files\EZWebGallery\2022-01-09\EZWebGallery.exe
Faulting module path: C:\Program 
Files\EZWebGallery\2022-01-09\CORE_RL_magick_.dll
Report Id: f433fe1b-92af-41b6-a9bd-4445b296aa97
Faulting package full name:
Faulting package-relative application ID:

Some detailed debugging information (Process Monitor trace)  is 
available for download here:

http://meccano.crabdance.com/pvr/EZWebGallery/

David Williams, Edmonton, Alberta, CANADA
***@***.***

**Comment by Pixinn** [comment]
I will open a specific issue in which I will answer.
